base_version: v0.5
data_table: default
duration: "30d"
fortran_diagnostics: []
initial_conditions: $IC_URL
diagnostics:
- chunks:
    time: 1
  name: state_after_timestep.zarr
  tensorboard: false
  times:
    frequency: 18000
    kind: interval
    times: null
  variables:
  - longitude
  - latitude
  - vertical_thickness_of_atmospheric_layer
  - pressure_thickness_of_atmospheric_layer
  - surface_pressure
  - eastward_wind
  - northward_wind
  - vertical_wind
  - air_temperature
  - specific_humidity
  - cloud_water_mixing_ratio
  - total_precipitation
  - ozone_mixing_ratio
  - land_sea_mask
  - total_soil_moisture
  - liquid_soil_moisture
  - soil_temperature
  - surface_temperature
  - canopy_water
  - sea_ice_thickness
  - snow_depth_water_equivalent
- chunks:
    time: 1
  name: physics_tendencies.zarr
  tensorboard: false
  times:
    frequency: 18000
    includes_lower: false
    kind: interval
    times: null
  variables:
  - tendency_of_air_temperature_due_to_fv3_physics
  - tendency_of_specific_humidity_due_to_fv3_physics
  - tendency_of_cloud_water_mixing_ratio_due_to_fv3_physics
  - tendency_of_eastward_wind_due_to_fv3_physics
  - tendency_of_northward_wind_due_to_fv3_physics
  - tendency_of_ozone_mixing_ratio_due_to_fv3_physics
  - tendency_of_pressure_thickness_of_atmospheric_layer_due_to_fv3_physics
namelist:
  namsfc:
    # these flags make the coarse run use the GRIB data for snoalb and vegetation
    # if not included, it will use the initial condition data (which may differ from GRIB file)
    # for more info see https://docs.google.com/document/d/1ndOG4u3gZ6kWJV6TqLh-E04n15tl9Ni55B2bavta1Cc/edit#heading=h.uqcex6mf4e10
    fabss: 0
    fabsl: 0
    fvmnl: 0
    fvmns: 0
    fvmxl: 0
    fvmxs: 0
    # for time-varying SSTs from GRIB
    ftsfs: 0
    # for time-varying sea ice from GRIB
    fsicl: 0
    fsics: 0
    faisl: 0
    faiss: 0
  atmos_model_nml:
    blocksize: -1
  coupler_nml:
    current_date:
    - 2016
    - $MONTH_INT
    - 1
    - 0
    - 0
    - 0
    days: 12
    hours: 0
    minutes: 0
    seconds: 0
  diag_manager_nml:
    flush_nc_files: true
  fv_core_nml:
    do_sat_adj: false
    nudge: false
    nudge_qv: false
    warm_start: false
    external_ic: true
    external_eta: false
    make_nh: true
    nggps_ic: true
    mountain: false
    na_init: 1
    nwat: 2
  gfdl_cloud_microphysics_nml:
    fast_sat_adj: false
  gfs_physics_nml:
    satmedmf: false
    hybedmf: true
    imp_physics: 99
    ncld: 1
    ldiag3d: true
    save_zc_microphysics: true
    emulate_zc_microphysics: false
zhao_carr_emulation:
  storage:
    # 5 hour sampling
    output_freq_sec:  18000
    save_nc: true
    save_zarr: false
