use_wandb: false
seed: 3
batch_size: 512
epochs: 50
nfiles_valid: 100
valid_freq: 2
out_url: /outputs/models/gscond
test_url: /data/test
train_url: /data/train
tensor_transform:
  - to: log_cloud_input
    source: cloud_water_mixing_ratio_input
    transform: {epsilon: 1e-10}
  - to: log_humidity_input
    source: specific_humidity_input
    transform: {epsilon: 1e-8}
  - to: log_humidity_after_last_gscond
    source: specific_humidity_after_last_gscond
    transform: {epsilon: 1e-8}
  - to: humidity_gscond_difference
    before: specific_humidity_input
    after: specific_humidity_after_gscond
  - to: humidity_gscond_difference_tscaled
    source: humidity_gscond_difference
    condition_on: air_temperature_input
    bins: 50
    min_scale: 1e-14
    fit_filter_magnitude: 1e-14
  - relative_humidity: relative_humidity
loss:
  optimizer:
    kwargs:
      learning_rate: 0.0001
    name: Adam
  metric_variables: []
  normalization_map:
    humidity_gscond_difference_tscaled:
      center: none
      scale: none
  loss_variables:
    - humidity_gscond_difference_tscaled
    - specific_humidity_after_gscond
  weights:
    humidity_gscond_difference_tscaled: 1.0
    specific_humidity_after_gscond: 50000.0
  bias_metric_variables:
    - humidity_gscond_difference
    - specific_humidity_after_gscond
model:
  architecture:
    kwargs:
      width: 256
      depth: 2
    name: dense
  input_variables:
  - air_temperature_input
  - specific_humidity_input
  - cloud_water_mixing_ratio_input
  - log_cloud_input
  - log_humidity_input
  - pressure_thickness_of_atmospheric_layer
  - air_temperature_after_last_gscond
  - specific_humidity_after_last_gscond
  - log_humidity_after_last_gscond
  - air_pressure
  - surface_air_pressure
  - surface_air_pressure_after_last_gscond
  - relative_humidity
  unscaled_outputs:
    - humidity_gscond_difference_tscaled
  normalize_default:
    center: per_feature
    scale: all
  selection_map: {}
  timestep_increment_sec: 900
transform:
  antarctic_only: false
  derived_microphys_timestep: 900
  use_tensors: true
  vertical_subselections: null

